### ISSUE TITLE
关于cookie

### ISSUE THREAD

**Issue by wy1ng** [sazn1314/MyActions#1]
没看明白，JD_COOKIE里应该直接填入cookie还是pt_key=****;pt_pin=***;？

**Comment by wy1ng** [comment]
另外，关于cookie的获取方法不太多。。。

**Comment by sazn1314** [comment]
https://github.com/sazs34/MyActions

去这边fork吧，这里的是自用的，经常调整可能报错的

**Comment by sazn1314** [comment]
https://github.com/lxk0301/scripts/issues/8#issuecomment-675837338

cookie的获取以及调整看这里就好了，很详细的
